name: AppSweep mobile application security testing
on: workflow_dispatch
jobs:
  upload-app-to-appsweep:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Access APPSWEEP_API_KEY
        env:
            APPSWEEP_API_KEY: ${{ secrets.APPSWEEP_API_KEY }}
        run: echo APPSWEEP_API_KEY=$APPSWEEP_API_KEY > $GITHUB_WORKSPACE/local.properties
      
      - name: Print APPSWEEP_API_KEY
        run: cat $GITHUB_WORKSPACE/local.properties
        
      - name: Upload app to AppSweep with Gradle
        run: ./gradlew uploadToAppSweepRelease --stacktrace
