name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: sudo echo "10.132.15.197 development.appsweep.guardsquare.com" | sudo tee -a /etc/hosts
      - run: ./gradlew app:assembleRelease
      - run: ./gradlew uploadToAppSweepRelease --stacktrace
