name: AppSweep mobile application security testing
on: workflow_dispatch
jobs:
  upload-app-to-appsweep:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Upload app to AppSweep with Gradle
        env:
            APPSWEEP_API_KEY: ${{ secrets.APPSWEEP_API_KEY }}
        uses: gradle/gradle-build-action@v2
        with:
          arguments: uploadToAppSweepRelease
